// apps/web/src/routes/auth/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { fade, slide, fly } from 'svelte/transition';
	import { FileCode2, Eye, EyeOff, Loader, ArrowRight, Sparkles } from 'lucide-svelte';

	let mode = $state<'login' | 'register'>('login');
	let loginValue = $state('');
	let username = $state('');
	let email = $state('');
	let password = $state('');
	let error = $state('');
	let loading = $state(false);
	let showPassword = $state(false);
	let mounted = $state(false);

	const API = 'http://localhost:8080/api';

	onMount(() => { mounted = true; });

	async function handleSubmit() {
		error = '';
		loading = true;
		try {
			if (mode === 'login') {
				const res = await fetch(`${API}/auth/login`, {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({ login: loginValue, password })
				});
				if (!res.ok) { error = 'Invalid credentials'; loading = false; return; }
				const data = await res.json();
				localStorage.setItem('forge_token', data.token);
				window.location.href = '/';
			} else {
				const res = await fetch(`${API}/auth/register`, {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({ username, email, password })
				});
				if (!res.ok) { const text = await res.text(); error = text; loading = false; return; }
				const data = await res.json();
				localStorage.setItem('forge_token', data.token);
				window.location.href = '/';
			}
		} catch { error = 'Connection error'; }
		loading = false;
	}

	function switchMode(m: 'login' | 'register') {
		if (m === mode) return;
		mode = m;
		error = '';
	}
</script>

{#if mounted}
<div class="min-h-screen flex items-center justify-center bg-surface-950 relative overflow-hidden">
	<!-- Aurora -->
	<div class="absolute inset-0 overflow-hidden pointer-events-none">
		<div class="absolute -top-40 -left-40 w-96 h-96 bg-forge-500/8 rounded-full blur-3xl animate-aurora" />
		<div class="absolute -bottom-40 -right-40 w-96 h-96 bg-accent-500/8 rounded-full blur-3xl animate-aurora" style="animation-delay: -3s" />
		<div class="absolute top-1/3 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-forge-500/5 rounded-full blur-3xl animate-aurora" style="animation-delay: -6s" />
	</div>

	<!-- Grid -->
	<div class="absolute inset-0 opacity-[0.02]" style="background-image: linear-gradient(rgba(255,255,255,.08) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.08) 1px, transparent 1px); background-size: 40px 40px;" />

	<div class="relative w-full max-w-sm mx-4" transition:fade={{ duration: 400 }}>
		<!-- Logo -->
		<div class="text-center mb-8" in:fade={{ duration: 600, delay: 100 }}>
			<div class="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-gradient-to-br from-forge-400 via-forge-500 to-accent-500 mb-4 shadow-lg shadow-forge-500/20">
				<FileCode2 size={26} class="text-white" />
			</div>
			<h1 class="text-2xl font-bold text-surface-100 tracking-tight">Forge</h1>
			<p class="text-sm text-surface-500 mt-1">by Veloro</p>
		</div>

		<!-- Card -->
		<div class="bg-surface-900/50 backdrop-blur-2xl border border-surface-700/40 rounded-2xl p-6 space-y-5" in:fade={{ duration: 400, delay: 200 }}>
			<!-- Tabs -->
			<div class="flex gap-1 bg-surface-950/50 rounded-lg p-1">
				<button
					onclick={() => switchMode('login')}
					class="flex-1 py-2 text-sm font-medium rounded-md transition-all duration-300"
					class:bg-forge-500={mode === 'login'}
					class:text-white={mode === 'login'}
					class:text-surface-400={mode !== 'login'}
					class:hover:text-surface-200={mode !== 'login'}
				>
					Sign In
				</button>
				<button
					onclick={() => switchMode('register')}
					class="flex-1 py-2 text-sm font-medium rounded-md transition-all duration-300"
					class:bg-forge-500={mode === 'register'}
					class:text-white={mode === 'register'}
					class:text-surface-400={mode !== 'register'}
					class:hover:text-surface-200={mode !== 'register'}
				>
					Register
				</button>
			</div>

			<form onsubmit={(e) => { e.preventDefault(); handleSubmit(); }} class="space-y-4">
				{#key mode}
					{#if mode === 'register'}
						<div in:fade={{ duration: 250, delay: 50 }} out:fade={{ duration: 150 }}>
							<label for="username" class="block text-xs font-medium text-surface-300 mb-1.5">Username</label>
							<input id="username" type="text" placeholder="your-username" bind:value={username} class="input-base text-sm" required />
						</div>
						<div in:fade={{ duration: 250, delay: 100 }} out:fade={{ duration: 150 }}>
							<label for="email" class="block text-xs font-medium text-surface-300 mb-1.5">Email</label>
							<input id="email" type="email" placeholder="you@example.com" bind:value={email} class="input-base text-sm" required />
						</div>
					{:else}
						<div in:fade={{ duration: 250, delay: 50 }} out:fade={{ duration: 150 }}>
							<label for="login" class="block text-xs font-medium text-surface-300 mb-1.5">Username or Email</label>
							<input id="login" type="text" placeholder="username or email" bind:value={loginValue} class="input-base text-sm" required />
						</div>
					{/if}
				{/key}

				<div>
					<label for="password" class="block text-xs font-medium text-surface-300 mb-1.5">Password</label>
					<div class="relative">
						<input id="password" type={showPassword ? 'text' : 'password'} placeholder="••••••••" bind:value={password} class="input-base text-sm pr-10" required />
						<button type="button" onclick={() => showPassword = !showPassword} class="absolute right-3 top-1/2 -translate-y-1/2 text-surface-400 hover:text-surface-200 transition-colors">
							{#if showPassword}<EyeOff size={16} />{:else}<Eye size={16} />{/if}
						</button>
					</div>
				</div>

				{#if error}
					<div class="text-sm text-red-400 bg-red-500/10 rounded-lg px-3 py-2 text-center" in:fade={{ duration: 200 }}>
						{error}
					</div>
				{/if}

				<button
					type="submit" disabled={loading}
					class="w-full py-2.5 bg-gradient-to-r from-forge-500 to-accent-500 hover:from-forge-400 hover:to-accent-400 
						   disabled:from-surface-700 disabled:to-surface-700 disabled:text-surface-500
						   text-white rounded-lg text-sm font-medium transition-all duration-300 
						   hover:shadow-lg hover:shadow-forge-500/25 active:scale-[0.97] 
						   flex items-center justify-center gap-2 group"
				>
					{#if loading}
						<Loader size={16} class="animate-spin" />
					{:else}
						<ArrowRight size={16} class="transition-transform duration-300 group-hover:translate-x-0.5" />
					{/if}
					{mode === 'login' ? 'Sign In' : 'Create Account'}
				</button>
			</form>

			<p class="text-xs text-surface-500 text-center">
				By continuing, you agree to the
				<a href="#" class="text-forge-400 hover:text-forge-300 transition-colors">Terms of Service</a>
			</p>
		</div>

		<!-- Features hint -->
		<div class="flex items-center justify-center gap-4 mt-6 text-xs text-surface-600" in:fade={{ duration: 600, delay: 500 }}>
			<span class="flex items-center gap-1"><Sparkles size={12} /> Self-hosted</span>
			<span class="flex items-center gap-1"><Sparkles size={12} /> Git hosting</span>
			<span class="flex items-center gap-1"><Sparkles size={12} /> Open source</span>
		</div>
	</div>
</div>
{/if}

// apps/site/src/pages/Auth.tsx
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Cpu, Github, ArrowRight, Sparkles } from "lucide-react";
import { useState } from "react";
import { login } from "@/api/auth";

export function AuthPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // const handleAuth = (user: string, password: string) => {
  //   console.log(user, password);
  // };

  const handleAuth = (email: string, password: string) => {
    login(email, password);
  };

  return (
    <div className="min-h-screen bg-[#030607] text-white flex items-center justify-center relative overflow-hidden selection:bg-emerald-500/30 font-sans">
      {/* AURORA / GLOW BACKGROUND */}
      <div className="absolute inset-0 z-0 overflow-hidden">
        <motion.div
          animate={{
            scale: [1, 1.2, 1],
            opacity: [0.18, 0.32, 0.18],
            x: [0, 50, 0],
            y: [0, -30, 0],
          }}
          transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
          className="absolute top-[-15%] left-[-15%] w-[900px] h-[900px] bg-emerald-500/20 rounded-full blur-[140px]"
        />
        <motion.div
          animate={{
            scale: [1, 1.15, 1],
            opacity: [0.16, 0.34, 0.16],
            x: [0, -40, 0],
            y: [0, 40, 0],
          }}
          transition={{
            duration: 12,
            repeat: Infinity,
            ease: "easeInOut",
            delay: 1,
          }}
          className="absolute bottom-[-15%] right-[-15%] w-[900px] h-[900px] bg-cyan-500/18 rounded-full blur-[140px]"
        />
        <div className="absolute top-[25%] right-[35%] w-[520px] h-[520px] bg-blue-500/10 rounded-full blur-[140px]" />
      </div>

      {/* SUBTLE GRID (masked) */}
      <div className="absolute inset-0 z-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:72px_72px] [mask-image:radial-gradient(ellipse_65%_60%_at_50%_45%,black,transparent)]" />

      <div className="w-full max-w-6xl grid lg:grid-cols-2 gap-20 z-10 px-6">
        {/* LEFT */}
        <div className="hidden lg:flex flex-col justify-center space-y-10">
          <motion.div
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-white/10 bg-white/5 backdrop-blur text-xs font-medium text-white/80 mb-6">
              <Sparkles className="w-3 h-3 text-emerald-300" />
              <span>System Online</span>
              <span className="ml-1 inline-flex h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_14px_rgba(52,211,153,0.8)]" />
            </div>

            <h1 className="text-6xl font-bold tracking-tight leading-[1.05]">
              Deployment{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-300 via-cyan-300 to-blue-300">
                for hardware.
              </span>
            </h1>

            <p className="mt-6 text-lg text-white/55 leading-relaxed max-w-md">
              Forge is your Git control plane with Spark integration for fleets.
              Soft UI, hard infrastructure.
            </p>
          </motion.div>

          <div className="grid grid-cols-2 gap-4 max-w-md">
            {[
              { label: "Uptime", val: "99.99%" },
              { label: "Deploy", val: "< 50ms" },
            ].map((item, i) => (
              <motion.div
                key={item.label}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 + i * 0.12, duration: 0.5 }}
                className="p-4 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-md"
              >
                <div className="text-white/45 text-sm">{item.label}</div>
                <div className="text-xl font-semibold mt-1">{item.val}</div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* RIGHT */}
        <div className="flex items-center justify-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.55, delay: 0.1 }}
            className="w-full max-w-[420px] relative group"
          >
            {/* BORDER GLOW (emerald -> cyan -> blue) */}
            <div className="absolute -inset-[1px] rounded-3xl opacity-70 blur-md group-hover:opacity-100 transition duration-700" />

            {/* INNER GLASS CARD */}
            <div className="relative rounded-3xl p-8 border border-white/10 bg-white/[0.06] backdrop-blur-xl shadow-2xl">
              <div className="flex flex-col items-center mb-8">
                <div
                  className="w-12 h-12 rounded-2xl flex items-center justify-center mb-4
                  bg-gradient-to-tr from-emerald-400/80 to-cyan-400/80 shadow-lg shadow-emerald-500/15"
                >
                  <Cpu className="text-white/80 w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold">Welcome Back</h2>
                <p className="text-white/45 text-sm mt-2">
                  Sign in to access your console
                </p>
              </div>

              <form className="space-y-5">
                <div className="space-y-2">
                  <Label className="text-xs font-medium text-white/60 ml-1">
                    Email
                  </Label>
                  <Input
                    placeholder="you@forge.dev"
                    className="h-12 rounded-2xl bg-white/5 border-white/10 text-white placeholder:text-white/25
                      focus:bg-white/10 focus:border-emerald-400/40 focus:ring-emerald-500/20 transition-all"
                    onChange={(e) => {
                      setEmail(e.target.value);
                    }}
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-xs font-medium text-white/60 ml-1">
                    Password
                  </Label>
                  <Input
                    type="password"
                    placeholder="••••••••"
                    className="h-12 rounded-2xl bg-white/5 border-white/10 text-white placeholder:text-white/25
                      focus:bg-white/10 focus:border-emerald-400/40 focus:ring-emerald-500/20 transition-all"
                    onChange={(e) => {
                      setPassword(e.target.value);
                    }}
                  />
                </div>

                {/* BUTTON (no pink) */}
                <Button
                  className="w-full h-12 rounded-2xl font-semibold transition-all hover:scale-[1.015]
                    bg-gradient-to-r from-emerald-500 to-cyan-500 text-white/80
                    shadow-lg shadow-emerald-500/15 hover:shadow-emerald-500/25"
                  onClick={() => {
                    handleAuth(email, password);
                  }}
                >
                  Sign In
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </form>

              <div className="mt-8 pt-6 border-t border-white/10">
                <Button
                  variant="outline"
                  className="w-full h-12 rounded-2xl border-white/10 bg-white/5 hover:bg-white/10 text-white/80 hover:text-white transition-all"
                >
                  <Github className="w-4 h-4 mr-2" />
                  Continue with GitHub
                </Button>
              </div>

              <div className="mt-6 text-center">
                <p className="text-xs text-white/30">
                  By signing in, you agree to our{" "}
                  <a
                    href="#"
                    className="text-white/60 hover:text-white underline"
                  >
                    Terms
                  </a>
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
